/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=/dev/null --include-runtime=false apps/worker/src/worker-configuration.d.ts` (hash: 042a9c684e647120713f4fa403703d79)
interface __BaseEnv_Env {
	ASSETS_BUCKET: R2Bucket;
	DB: D1Database;
	MEDIA_ICON_INDEX_REFRESH_QUEUE: Queue;
	ASSETS: Fetcher;
	SETUP_ENABLED: "true";
	RENEWLET_MAINTENANCE_MODE: "false";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SETUP_ENABLED" | "RENEWLET_MAINTENANCE_MODE">> {}
}
