// 云备份 schema 的事实源在 shared；前端只 re-export，避免 Docker/Worker API shape 分叉。
export {
  CLOUD_BACKUP_DEFAULT_RETENTION,
  CLOUD_BACKUP_DEFAULT_SCHEDULE_TIME,
  CLOUD_BACKUP_DEFAULT_SCHEDULE_WEEKDAY,
  CLOUD_BACKUP_MAX_RETENTION,
  CLOUD_BACKUP_MAX_SNAPSHOT_BYTES,
  CLOUD_BACKUP_RAW_RESPONSE_TEXT_MAX_CHARS,
  cloudBackupConfigResponseSchema,
  cloudBackupConfigSchema,
  cloudBackupConfigUpdateSchema,
  cloudBackupCreateSnapshotRequestSchema,
  cloudBackupCreateSnapshotResponseSchema,
  cloudBackupDeleteSnapshotResponseSchema,
  cloudBackupErrorDetailsSchema,
  cloudBackupPolicySchema,
  cloudBackupProviderSchema,
  cloudBackupScheduleTimeSchema,
  cloudBackupScheduleFrequencySchema,
  cloudBackupScheduleWeekdaySchema,
  cloudBackupTargetStatusSchema,
  cloudBackupSnapshotManifestSchema,
  cloudBackupSnapshotSchema,
  cloudBackupSnapshotsResponseSchema,
  cloudBackupTestRequestSchema,
  cloudBackupTestResponseSchema,
} from "@renewlet/shared/schemas/cloud-backup";

export type {
  CloudBackupConfig,
  CloudBackupConfigResponse,
  CloudBackupConfigUpdate,
  CloudBackupCreateSnapshotRequest,
  CloudBackupCreateSnapshotResponse,
  CloudBackupDeleteSnapshotResponse,
  CloudBackupErrorDetails,
  CloudBackupPolicy,
  CloudBackupProvider,
  CloudBackupProviderPolicyMap,
  CloudBackupProviderStatusMap,
  CloudBackupScheduleFrequency,
  CloudBackupScheduleTime,
  CloudBackupScheduleWeekday,
  CloudBackupSnapshot,
  CloudBackupSnapshotManifest,
  CloudBackupSnapshotsResponse,
  CloudBackupTargetStatus,
  CloudBackupTestRequest,
  CloudBackupTestResponse,
} from "@renewlet/shared/schemas/cloud-backup";
